services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DIRECTUS_URL: ${DIRECTUS_URL:-}
      DIRECTUS_STATIC_TOKEN: ${DIRECTUS_STATIC_TOKEN:-}
      PORT: ${PORT:-3000}
      CORS_ORIGIN: ${CORS_ORIGIN:-}
    ports:
      - "5174:3000"
    restart: unless-stopped
